name: 'Cache test'

on: [push]

jobs:
  test:
    runs-on: [self-hosted]
    name: A job to test cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: corca-ai/local-cache@develop
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - name: Test cache-hit
        continue-on-error: true
        run: |
          echo "Test cache hit: ${{ steps.cache.outputs.cache-hit }}"
          test -d node_modules ; echo "$?"
      - name: Install dependencies
        continue-on-error: true
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          test -d /tmp/.cache/${{ hashFiles('package-lock.json') }} ; echo "$?"
